config/routes.rb
Rails.application.routes.draw do
  root "main#index" 
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    EMAIL_REGEX = /\A[a-z0-9\+\-_\.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: EMAIL_REGEX }
    has_secure_password 
    has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destory]

    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render "new"
        end
    end

    def update
       if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
       else
        render 'edit'
       end

    end

    def destroy 
        @article.destroy

        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
          flash[:notice] = "Category successfully created"
          redirect_to @category
        else
          render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
          flash[:notice] = "Category was successfully updated"
          redirect_to @category
        else
          flash[:alert] = "Something went wrong"
          render 'edit'
        end
    end
    

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
       if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform that action"
        redirect_to categories_path
       end
    end
    
    
    
    
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        redirect_to articles_path if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
end

    
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def edit

    end

    def update

        if @user.update(user_params)
            flash[:notice] = "Profile updated successfully"
            redirect_to @user
        else
            render "edit"
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Alpha Blog, #{@user.username}. You have successfully signed up"
            redirect_to articles_path
        else
            render "new"
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_for(user, options = { size: '150x150' })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        robot_url = "https://robohash.org/#{hash}.png/bgset_any?size=#{size}"
        image_tag(robot_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
     
    end
end

app/views/articles/_article.html.erb
<div class="container">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col" colspan="3">Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @articles.each do |article| %>
                <tr>
                    <td><%= article.title %></td>
                    <td><%= article.description %></td>
                    <% if article.categories.any? %>
                        <td class="mt-2 mb-2">
                            <%= render article.categories %>
                        </td>
                        <% else %>
                            <td>No category</td>
                    <% end %>
                    <td><%= link_to 'Show', article_path(article.id) %></td>
                    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                        <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
                        <td><%= link_to 'Delete', article_path(article.id), method: :delete, data: { confirm: "Confirm?" } %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>

    <p>
    <%= link_to "Create new article", new_article_path %>
    </p>        
</div>

app/views/articles/_form.html.erb
<div class="container">

    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "share/errors", obj: @article %>
            <%= form_with model: @article, class:"shadow p-3 mb-3 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title" %>
                    </div>
                </div>


                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Write something..." %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :category, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
                            <%= b.label %>
                            <%= b.check_box class: "form-check-input" %>
                        <% end %>
                    </div>
                </div>

                    
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>

            <%= link_to "[ Cancel and Return to List ]", articles_path %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>

<%= render 'article' %>

<div class="flickr_pagination">
    <%= will_paginate @posts, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create New Article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<div class="container">
    <h1 class="text-center mt-4">Article Details</h1>
    <div class="row justify-content-center">
        <div class="col-10">

            <div class="list-group">
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1"><%= @article.title %></h5>
                        <small>3 days ago</small>
                    </div>
                    <p class="mb-1"><%= @article.description %></p>
                    <% if @article.categories.any? %>
                        <div class="mt-2 mb-2">
                            <%= render @article.categories %></br>
                        </div>
                    <% end %>
                    <small>By <%= @article.user.username %></small>

                    <div>
                        <%= link_to "Edit", edit_article_path(@article)%> |
                        <% if logged_in? && (@article.user == current_user || current_user.admin?) %> 
                            <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Confirm?" } %> |
                            <%= link_to "Return to List", articles_path %>
                        <% end %>
                    </div>
                </>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-dark" %>

app/views/categories/_form.html.erb
<%= render "share/errors", obj: @category %>
<%= form_with model: @category, class:"shadow p-3 mb-3 bg-info rounded", local: true do |f| %>
    <div class="form-group row">
        <%= f.label :name, "Category name:", class: "col-2 col-form-label text-light" %>
        <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
        </div>
    </div>

                
    <div class="form-group row justify-content-center">
        <%= f.submit "Save", class: "btn btn-outline-light btn-lg" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>

<div class="container">

    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'form' %>
            <%= link_to "[ Cancel and Return to List ]", categories_path(@category) %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing All Categories</h1>

<div class="container">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Title</th>
            <th scope="col">Articles</th>
        </thead>

        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td><%= link_to category.name, category_path(category) %></td>
                    <td><%= pluralize(category.articles.count, "article") %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <% if logged_in? && current_user.admin? %>
        <p>
            <%= link_to "Create new category", new_category_path %>
        </p>
    <% end %>

    <div class="flickr_pagination">
        <%= will_paginate @posts, :container => false %>
    </div>        
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container">

    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "share/errors", obj: @category %>
            <%= form_with model: @category, class:"shadow p-3 mb-3 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :name, "Category name:", class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
                    </div>
                </div>

                    
                <div class="form-group row justify-content-center">
                    <%= f.submit "Create", class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>

            <%= link_to "[ Cancel and Return to List ]", articles_path %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h1>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Caroline Cagnin", "http://github.com/ccagnin", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= "(Admin)" if current_user.admin? %> Profile [<%=current_user.username %>]
                </a>
                <ul class="dropdown-menu">
                  <%= link_to "View Profile", user_path(current_user), class: "dropdown-item"%>
                  <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item"%>
                  <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" }%>
                </ul>
              </li>
            </li> 
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item"%>
            <% end %>
               <%= link_to "View Articles", articles_path, class: "dropdown-item"%>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
            <% end %>
               <%= link_to "View Categories", categories_path, class: "dropdown-item"%>
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

  <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </body>

</html>

app/views/main/index.html.erb
<%# <h1>Welcome to home page</h1> %>
<div id="page-content">
    <div class="container-fluid">
        <div class="card text-bg-dark text-center">
            <div class="card-img-overlay">
                <h5 class="card-title">Hello, world!</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
            <div class="btn-container">
                <%= link_to "Sign Up!", signup_path, class: "btn btn-outline-success" %>
                <%= link_to "Login", login_path, class:"btn btn-outline-success" %>
            </div>
        </div>
    </div>
</div>

app/views/share/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved: </h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "share/errors", obj: @user %>
            <%= form_with model: @user, class:"shadow p-3 mb-3 bg-info rounded", local: true do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
                    </div>
                </div>


                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
                    </div>
                </div>

                    
                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: "btn btn-outline-light btn-lg") %>
                </div>
            <% end %>

            <%= link_to "[ Cancel and Return to List ]", articles_path %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
    <table class="table">
        <thead>
            <tr>
            <th scope="col">Image</th>
            <th scope="col">User</th>
            <th scope="col" colspan="3">Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td><%= link_to avatar_for(user, size: '50x50'), user_path(user.id) %></td>
                    <td><%= user.username %></td>
                    <td><%= link_to 'View Profile', user_path(user.id) %></td>
                    <td><%= pluralize(user.articles.count, "article") %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <p>
    <%= link_to "Create new article", new_article_path %>
    </p>

    <div class="flickr_pagination">
        <%= will_paginate @users, :container => false %>
    </div>        
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= avatar_for @user %>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h1>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>